# Generated by Django 3.1.3 on 2020-12-10 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_income_spending'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='Spending',
        ),
    ]
