# Generated by Django 3.1.3 on 2020-12-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201210_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
