# Generated by Django 3.1.3 on 2020-12-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201210_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('SLRY', 'Salary'), ('PRFT', 'Profit'), ('ITRT', 'Interest'), ('DVDT', 'Divident'), ('RNTL', 'Rental'), ('CPTL', 'Capital'), ('RYLT', 'Royalty'), ('GIFT', 'Gift'), ('OTRS', 'Others')], default='SLRY', max_length=4, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='income',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date/Time'),
        ),
        migrations.AlterField(
            model_name='income',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='income',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date/Time'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date/Time'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.CharField(choices=[('AED', 'AED'), ('AUD', 'AUD'), ('BRL', 'BRL'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('CLP', 'CLP'), ('CNY', 'CNY'), ('COP', 'COP'), ('CZK', 'CZK'), ('DKK', 'DKK'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('HKD', 'HKD'), ('HUF', 'HUF'), ('IDR', 'IDR'), ('ILS', 'ILS'), ('INR', 'INR'), ('JPY', 'JPY'), ('KRW', 'KRW'), ('MDL', 'MDL'), ('MXN', 'MXN'), ('MYR', 'MYR'), ('NOK', 'NOK'), ('NZD', 'NZD'), ('PHP', 'PHP'), ('PLN', 'PLN'), ('RON', 'RON'), ('RUB', 'RUB'), ('SAR', 'SAR'), ('SEK', 'SEK'), ('SGD', 'SGD'), ('THB', 'THB'), ('TRY', 'TRY'), ('TWD', 'TWD'), ('USD', 'USD'), ('ZAR', 'ZAR')], default='USD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date/Time'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='category',
            field=models.CharField(choices=[('UTLT', 'Utilities'), ('RENT', 'Rent'), ('INVC', 'Invoices'), ('SHPG', 'Shopping'), ('FOOD', 'Food'), ('EDCN', 'Education'), ('FUN', 'Fun'), ('INVT', 'Investment'), ('OTRS', 'Others')], default='UTLT', max_length=4, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date/Time'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date/Time'),
        ),
    ]
