# Generated by Django 3.1.3 on 2020-12-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201226_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(max_length=4, verbose_name='Category'),
        ),
    ]
