# Generated by Django 3.1.3 on 2021-01-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210111_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='category',
            field=models.CharField(choices=[('Utilities', 'Utilities'), ('Rent', 'Rent'), ('Invoices', 'Invoices'), ('Shopping', 'Shopping'), ('Food', 'Food'), ('Education', 'Education'), ('Fun', 'Fun'), ('Investment', 'Insetment'), ('Others', 'Others')], default='Utilities', max_length=10, verbose_name='Category'),
        ),
    ]
