# Generated by Django 3.1.3 on 2021-01-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210111_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accept_terms_and_conditions',
            field=models.BooleanField(default=False, verbose_name='Accept terms and contidions'),
        ),
    ]
