# Generated by Django 3.1.4 on 2021-01-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_accept_terms_and_conditions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='do_not_marketing_email',
            new_name='marketing_email',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
