# Generated by Django 3.1.3 on 2021-01-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210113_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
