# Generated by Django 3.1.3 on 2021-01-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20210122_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
