# Generated by Django 3.1.3 on 2021-01-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20210122_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='accept_terms_and_conditions',
            new_name='accept_terms_conditions_and_security_policy',
        ),
        migrations.RemoveField(
            model_name='user',
            name='marketing_email',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_verified',
            field=models.BooleanField(default=False, verbose_name='Phone Number Verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='send_marketing_emails',
            field=models.BooleanField(default=False, verbose_name='Send marketing emails'),
        ),
    ]
