# Generated by Django 3.1.4 on 2021-01-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210124_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accept_terms_conditions_and_security_policy',
            field=models.BooleanField(default=False, verbose_name='Accept Terms and Conditions, Data Security Policy'),
        ),
    ]
