# Generated by Django 3.1.3 on 2021-02-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20210125_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='img/default.jpg', upload_to='img/profile_pics', verbose_name='Avatar'),
        ),
    ]
