# Generated by Django 3.1.3 on 2021-02-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20210218_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pro_membership',
            field=models.BooleanField(default=False, verbose_name='Pro Membership'),
        ),
    ]
