# Generated by Django 3.1.3 on 2021-02-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_user_pro_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='account',
        ),
        migrations.RemoveField(
            model_name='spending',
            name='account',
        ),
    ]
