# Generated by Django 3.1.3 on 2021-02-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20210220_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='account',
        ),
        migrations.RemoveField(
            model_name='spending',
            name='account',
        ),
    ]
