# Generated by Django 3.1.3 on 2021-02-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_auto_20210221_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='account',
        ),
        migrations.RemoveField(
            model_name='spending',
            name='account',
        ),
    ]
