# Generated by Django 3.1.3 on 2021-02-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='full_image',
            field=models.ImageField(default='full_blog_image.jpg', upload_to='blog_pics', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='post',
            name='medium_image',
            field=models.ImageField(default='medium_blog_image.jpg', upload_to='profile_pics', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='post',
            name='small_image',
            field=models.ImageField(default='small_blog_image.jpg', upload_to='profile_pics', verbose_name='Avatar'),
        ),
    ]
