# Generated by Django 3.1.3 on 2021-02-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210206_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='full_image',
            field=models.ImageField(default='img/full_blog_image.jpg', upload_to='img/blog_pics', verbose_name='Full Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='medium_image',
            field=models.ImageField(default='img/medium_blog_image.jpg', upload_to='img/blog_pics', verbose_name='Medium Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='small_image',
            field=models.ImageField(default='img/small_blog_image.jpg', upload_to='img/blog_pics', verbose_name='Small Image'),
        ),
    ]
