# Generated by Django 3.1.3 on 2020-12-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name="Message's Description")),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('person_type', models.CharField(choices=[('CLNT', 'Client'), ('PCLT', 'Pro Client'), ('STFF', 'Stuff')], default='CLNT', max_length=4, verbose_name='Person Type')),
            ],
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Newsletter Email'),
        ),
    ]
