# Generated by Django 3.1.3 on 2020-12-17 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201217_0833'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
